original_repo: https://github.com/vlctechhub/yoconcilio

volunteers_form: ""
mentors_form: ""
attendees_form: ""

keywords: "tecnología, evento, charla, vlctechhub, valencia, conciliación, feminismo, trabajo, infancia, coloquio"
title: "Yo concilio, tú concilias, ella concilia - VLCTechHub"
description: "¿Qué es la conciliación exactamente? ¿Cómo podemos ejercerla? ¿Qué opciones hay? ¿Que está haciendo la gente a nuestro alrededor? Vente el próximo sábado 20 de septiembre y aclaremos las dudas entre tod@s!"
ogimage: ""

sass:
    sass_dir: assets/_sass
    style: compressed
